testing policy validation

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -69,7 +69,14 @@ jobs:
       - name: Validate IAM Policies
         run: |
           for file in $(find policies/ -name "*.json"); do
-            aws accessanalyzer validate-policy --policy-type IDENTITY_POLICY --policy-document file://$file
+            echo "Validating $file"
+            output = $(aws accessanalyzer validate-policy --policy-type IDENTITY_POLICY --policy-document file://$file)
+            echo "$output"
+            if echo "$output" | grep -q '"findingType": "ERROR"'; then
+              error = $(echo "$output" | jq -r ".findings[].issueCode")
+              echo "Policy validation failed for $file with ERROR: $error findings"
+              exit 1
+            fi
           done
 
       # - name: Deploy with SST
